--Resumo do somatório da quantidade de produtos por categoria
SELECT
	c.NOME AS NOME_CATEGORIA,
	SUM(p.QUANTIDADE) AS QUANTIDADE_PRODUTOS
FROM 
	PRODUTO p
INNER JOIN
	CATEGORIA c ON c.ID = p.CATEGORIA_ID
WHERE
	p.DATACRIACAO BETWEEN '2025-05-01' AND '2025-05-31' AND ATIVO = 1
GROUP BY
	c.NOME
ORDER BY
	QUANTIDADE_PRODUTOS DESC;
GO


--Resumo da média de preço de produtos por categoria
SELECT
	c.NOME AS NOME_CATEGORIA,
	AVG(p.PRECO) AS MEDIA_PRECO
FROM 
	PRODUTO p
INNER JOIN
	CATEGORIA c ON c.ID = p.CATEGORIA_ID
WHERE
	p.DATACRIACAO BETWEEN '2025-05-01' AND '2025-05-31' AND ATIVO = 1
GROUP BY
	c.NOME
ORDER BY
	MEDIA_PRECO DESC;
GO


